// <auto-generated />
namespace Clustering.Model.Seed
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExpandableDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExpandableDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201510281138522_ExpandableDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
